### PR TITLE
[API-2970] Update Router SDK to support onlyTestnets field

### PR DESCRIPTION
**Pull request by zrbecker**
Adds onlyTestnets field to assets/chains/venues.

### CODE REVIEW

**Comment by NotJeremyLiu** [comment]
One thing you will need to do is add a changeset to this, which will be a major bump as its a breaking change, cc @codingki this is right?

**Comment by codingki** [comment]
yes this will be a major bump, please fix the test `src/__test__/client.test.ts` first

**Comment by zrbecker** [comment]
> yes this will be a major bump, please fix the test `src/__test__/client.test.ts` first

I think I fixed the test, how do I add a changeset?

**Comment by zrbecker** [comment]
> > yes this will be a major bump, please fix the test `src/__test__/client.test.ts` first
> 
> I think I fixed the test, how do I add a changeset?

nvm i found the instructions

**Comment by zrbecker** [comment]
@codingki should be good for review now

**Review by codingki — APPROVED** [review]

**Pull request merged**
